<div class="container">
    <div class="block_notifications">
        <p>Dear Client,</p>
        <p>YOUR ACCOUNT HAS BEEN SUCCESSFULLY ACTIVATED, WE REQUEST YOU TO READ THE TERMS AND CONDITIONS, RISK DECLARATIONS AND PRIVACY POLICY CAREFULLY AND IF YOU DOUBT, SEEK ADVICE ON YOUR INVESTMENTS.</p>
        <p>Si desea recibir una copia de estos documentos haga click <a href="javascript:void(0)">aqui</a></p>
        <h1>TERMS AND CONDITIONS</h1>
        <p>{{ isset($data['NOMBRE_DEL_BROKER']) ? $data['NOMBRE_DEL_BROKER'] : 'EL BROKER' }} Legal information</p>
        <p>Cualquier persona que acceda a esta página web, las páginas contenidas en ella y los productos, servicios, información, herramientas y material contenido o descrito en este documento (el "Sitio web") acepta implícitamente los términos y condiciones (los "Términos") que se detallan a continuación.</p>
        <p>Los Términos están sujetos a cambios sin previo aviso, de vez en cuando a exclusivo criterio de EL BROKER. Por lo tanto, se recomienda revisar estos Términos siempre que se acceda a este sitio web. El acceso y el uso de este sitio web pueden estar restringidos o finalizados en cualquier momento.</p>
        <p>El uso de este sitio web puede ser monitoreado, rastreado y registrado. Cualquiera que use este sitio web consiente expresamente tal monitoreo, seguimiento y registro.</p>
        <ol>
            <li>Acceso sujeto a restricciones locales
                <p>
                    La información en este sitio web no está destinada a su uso o distribución a ninguna persona física o jurídica en ninguna jurisdicción o país donde (i) la distribución, publicación o uso de dicha información sea contraria a la ley o las disposiciones reglamentarias; o (ii) dicha distribución está prohibida sin la obtención de las licencias o autorizaciones necesarias por parte de EL BROKER y dichas licencias o autorizaciones no han sido obtenidas.
                    Las personas físicas o jurídicas respecto de las cuales se aplican tales prohibiciones, ya sea por su nacionalidad, su lugar de residencia o por otros motivos, no deben acceder ni utilizar este sitio web.
                    Los materiales en este sitio web no están dirigidos a personas de los Estados Unidos.
                </p>
            </li>
            <li>Productos y servicios
                <p>Los productos y servicios que se muestran en este sitio web pueden no ser elegibles para la venta o estar disponibles para residentes de ciertos países o determinadas categorías de inversores. Consulte los términos y condiciones aplicables, como las restricciones de ventas o las notas clave específicas del producto para obtener más información. Cualquier material disponible en este sitio web no tiene en cuenta los objetivos de inversión específicos, la situación financiera o las necesidades particulares de ningún destinatario específico. No se proporciona ninguna representación o garantía, ya sea expresa o implícita, en relación con la exactitud, integridad o fiabilidad de los materiales, ni son una declaración completa de los valores, mercados o desarrollos a los que se hace referencia en este documento. Los materiales no deben ser considerados por los destinatarios como un sustituto del ejercicio de su propio juicio. Cualquier opinión está sujeta a cambios sin previo aviso y puede diferir o ser contraria a las opiniones expresadas por otras áreas comerciales de EL BROKER como resultado del uso de diferentes supuestos y criterios.</p>
            </li>
            <li>Ninguna oferta o recomendación
                <p>La información, opiniones, productos, datos, servicios, herramientas y documentos contenidos o descritos en este sitio web no deben interpretarse ni entenderse como ninguna forma de promoción, recomendación, incentivo, oferta o solicitud para (i) comprar o vender ningún instrumento de inversión, (ii) realizar cualquier otra transacción, o (iii) participar en otras transacciones legales. Se brindan solo con fines informativos.</p>
                <p>Los instrumentos y servicios de inversión descritos pueden no ser adecuados para todos los inversores o pueden no estar disponibles. Antes de tomar decisiones de inversión, los inversores deben llevar a cabo una investigación independiente exhaustiva y obtener todos los consejos profesionales necesarios para todas las cuestiones, incluida la elegibilidad para realizar dicha inversión en términos de la ley aplicable.</p>
            </li>
            <li>No representa servicios de asesoría
                <p>Nada en este sitio web constituye asesoramiento sobre inversión, legal, contable o impositivo, ni una manifestación de que cualquier inversión o estrategia es adecuada o apropiada para circunstancias individuales, o constituye una recomendación personal para cualquier inversor específico. Antes de tomar cualquier decisión de inversión, el inversionista debe comprender completamente los riesgos y méritos económicos y hacer su propia determinación de que la inversión es coherente con sus necesidades particulares de inversión, objetivos y circunstancias financieras, y que puede asumir el riesgo. EL BROKER recomienda que los inversionistas evalúen de forma independiente, con un asesor profesional, los riesgos y las consecuencias financieras, legales, reglamentarias, crediticias, impositivas y contables específicas. Ninguna información contenida o accedida desde este sitio web debe interpretarse como la creación de una relación contractual entre los proveedores de dicha información y los usuarios del sitio web.</p>
            </li>
            <li>Investigación
                <p>La información en este sitio web no es un producto del Departamento de Investigación de EL BROKER y, por lo tanto, no está sujeta a requisitos legales con respecto a la independencia de la investigación de inversiones.</p>
            </li>
            <li>Declaraciones prospectivas
                <p>Este sitio web puede contener declaraciones que constituyen "declaraciones prospectivas". Si bien estas declaraciones prospectivas pueden representar el juicio de EL BROKER y las expectativas futuras, una serie de riesgos, incertidumbres y otros factores importantes podrían causar que los desarrollos y resultados reales difieran materialmente de las expectativas de EL BROKER. EL BROKER no tiene la obligación (y renuncia expresamente a tal obligación) de actualizar o modificar sus declaraciones prospectivas, ya sea como resultado de nueva información, eventos futuros o de otro tipo.</p>
            </li>
            <li>Riesgos
                <p>El rendimiento pasado no debe tomarse como una indicación o garantía de rendimiento futuro, y no se hace ninguna representación o garantía, expresa o implícita, con respecto al rendimiento futuro. Invertir implica riesgos, incluida una pérdida parcial o incluso total de su capital invertido. El precio, el valor y los ingresos de valores o instrumentos financieros pueden disminuir o aumentar. Ciertas inversiones están sujetas a una alta volatilidad y pueden experimentar caídas repentinas y grandes en su valor. Las pérdidas pueden igualar o superar la inversión original: no se puede garantizar que se logre el objetivo de inversión de ningún producto o que no se sufran pérdidas sustanciales. Los valores e instrumentos financieros denominados en moneda extranjera están sujetos a fluctuaciones en los tipos de cambio que pueden tener un efecto positivo o adverso en el valor, precio o ingreso de dichos valores o instrumentos financieros. Es posible que algunas inversiones no sean fáciles de realizar y que no sea posible venderlas o realizarlas de inmediato, lo que puede dar como resultado la venta y realización de esas inversiones a un precio mucho más bajo. De manera similar, puede resultar difícil obtener información confiable sobre el valor o los riesgos a los que se expone dicha inversión. También hay consideraciones de riesgo especiales asociadas con inversiones internacionales y globales (especialmente mercados emergentes), inversiones de pequeñas empresas, fondos de una sola industria o estrategias de inversión, fondos de un solo país o regionales o estrategias de inversión, u otras estrategias de inversión especiales, agresivas o concentradas , como el uso de apalancamiento o derivados. Los inversores asumen efectivamente estos riesgos.</p>
            </li>
            <li>Excepción de Garantías
                <p>EL BROKER ha ejercido el máximo cuidado al compilar la información contenida en este sitio web. Sin embargo, EL BROKER no afirma ni garantiza (ya sea de forma expresa o implícita) que la información publicada en este sitio web sea precisa, confiable, actualizada o completa. En particular, EL BROKER no tiene obligación alguna de actualizar o eliminar información obsoleta u opiniones de este sitio web o marcarlas como desactualizadas. La información y opiniones contenidas en este sitio web están sujetas a cambios en cualquier momento sin previo aviso. Además, no se otorga ninguna garantía de que este sitio web operará libre de errores o sin interrupción, que se corregirán los fallos, o que este sitio web y los servidores a los que se accede con información estarán libres de virus, caballos de Troya, gusanos, bombas de software u otros componentes y programas dañinos y EL BROKER no acepta ninguna responsabilidad al respecto. Toda la información disponible en este sitio web, incluidos, entre otros, datos del mercado financiero, datos de precios, informes, investigaciones y otra información financiera se basa en fuentes cuidadosamente seleccionadas que se consideran confiables. Toda la información se proporciona a los usuarios "tal como está" y "según disponibilidad" sin ninguna representación o garantía expresa o implícita en cuanto a calidad, originalidad, no infracción de los derechos de propiedad intelectual o idoneidad para un fin determinado.</p>
            </li>
            <li>Sin responsabilidad
                <p>Independientemente de cualquier disposición contradictoria en estos Términos o cualquier otro acuerdo aplicable, EL BROKER, cualquier afiliado, incluidos o cualquier director, agente, empleado o subcontratista, en ningún caso será responsable de cualquier directa o pérdida o daño sufrido por los fondos de los clientes, que incluye pero no se limita a la pérdida de beneficios, capital disponible, depósitos, futuros incrmentos, comisiones, o cualquier otro recurso propiedad del cliente que pueda sufrir como resultado de la información provista en este sitio web, de informaciones provistas por cualquier empleado, funcionario, socio, asociado o representante.</p>
            </li>
            <li>Posibles conflictos de interés
                <p>EL BROKER, sus directores o empleados pueden haber invertido anteriormente, pueden estar invirtiendo o pueden invertir en el futuro en instrumentos de inversión con respecto a los cuales se proporciona información u opiniones en este sitio web. También es posible que EL BROKER haya proporcionado anteriormente, que actualmente brinde o que en el futuro prestará servicios a los emisores de dichos instrumentos de inversión, incluidos, por ejemplo, finanzas corporativas o servicios de creación de mercado. Además, es posible que los empleados o directores de EL BROKER hayan realizado anteriormente, estén desempeñando actualmente o realizarán en el futuro ciertas funciones de instrumentos de inversión, p. sirviendo como director. EL BROKER, sus directores o empleados podrían por lo tanto tener un interés en el rendimiento futuro de los instrumentos de inversión.</p>
            </li>
            <li>Propiedad intelectual, derecho de autor y derechos de marca
                <p>Todos los componentes de este sitio web están protegidos por leyes de propiedad intelectual y son propiedad de EL BROKER o de terceros. Los usuarios no deben adquirir ningún derecho, incluidos los derechos sobre cualquier software, marcas registradas o componentes de este sitio web, al descargar o imprimir cualquier material de este sitio web. Los avisos de derechos de autor y las marcas comerciales no pueden modificarse ni eliminarse. Los componentes de este sitio web no pueden reproducirse en todo o en parte de ninguna manera o forma (incluida la forma electrónica o impresa) sin el consentimiento previo por escrito de EL BROKER y a menos que se proporcione un reconocimiento completo de la fuente.</p>
                <p>Los usuarios no pueden crear hipervínculos o enlaces en línea desde otros sitios web a este sitio web sin el previo consentimiento por escrito de EL BROKER.</p>
            </li>
            <li>Transferencia / procesamiento de datos
                <p>EL BROKER llama expresamente la atención de los usuarios sobre el hecho de que los datos se transfieren a través de redes públicas como internet o servicios de correo electrónico, a los que cualquier persona puede acceder. EL BROKER no puede garantizar la confidencialidad de los mensajes o documentos enviados a través de dichas redes públicas. Cualquier persona que envíe información personal (como nombres y direcciones de remitentes y destinatarios) a través de una red pública debe saber que terceros pueden verla, almacenarla y usarla sin su permiso. Por lo tanto, los terceros pueden deducir cuentas existentes y prospectivas y relaciones comerciales. Incluso si el remitente y el destinatario se encuentran en el mismo país, los datos transferidos entre ellos a menudo pasan por otros países, incluidos aquellos que no ofrecen el mismo nivel de protección de datos que el país en cuestión, sin estar sujetos a ningún tipo de control. Los datos pueden perderse o ser interceptados por terceros no autorizados durante el proceso de transferencia. EL BROKER no acepta ninguna responsabilidad por la seguridad de los datos transferidos a través de Internet o por la pérdida de datos directa o indirecta. Por motivos de seguridad y protección de datos, se recomienda a los usuarios que se pongan en contacto con EL BROKER a través de otros medios de comunicación.</p>
            </li>
            <li>Cláusula de separabilidad
                <p>En la medida en que cualquier disposición de estos Términos sea encontrada por un tribunal o autoridad competente como inválida, ilegal o inaplicable en cualquier jurisdicción, dicha disposición se considerará no como parte de este descargo de responsabilidad, pero dicha determinación no afectará la validez o la legalidad. o la aplicabilidad del resto de estos Términos en esa jurisdicción, ni afectará la validez, legalidad o aplicabilidad de estos Términos en ninguna otra <a href="javascript:void(0)">jurisdicción</a></p>
            </li>
        </ol>
        <h1>RISK CLAUSE</h1>
        <ol>
            <li>Todas las operaciones que ejecuta EL BROKER (AQUÍ PODERLO PERSONALIZAR COMO LOS OTROS DISCLAIMERS) son por orden y cuenta del Cliente, por lo que EL BROKER no asumirá responsabilidad por el resultado económico de las transacciones que el Cliente ordene llevar a cabo.</li>
            <li>Las órdenes que se den, quedarán grabadas, por lo que se le informa al cliente que estará trabajando bajo la modalidad Spot, por ello, las órdenes tendrán una vigencia de 48 horas para ingresarlas al mercado, debido a lo anterior, es muy importante que se entienda bien la operación y los riesgos que va a ordenar. </li>
            <li>El cliente debe de recordar que no tiene la obligación de operar, por lo cual si en algún momento, una operación no le es suficientemente clara o satisfactoria para sus intereses, no deberá ordenar la operación.</li>
            <li>El cliente deberá decidir libremente su participación en el mercado, monto máximo a arriesgar y activo a operar, en caso de que el cliente sienta que está siendo inducido a realizar una operación que no desee realizar, será obligación del cliente reportar este hecho a la Gerencia de Atención al cliente, antes de realizar cualquier transacción </li>
            <li>Dentro de cualquier mercado especulativo, nadie le puede garantizar ningún beneficio, o siquiera la evasión de una pérdida por lo que una vez que usted de cualquier orden dentro del mercado, usted estará asumiendo todos los riesgos que la misma operación pueda acarrear. Es importante que el cliente considere cuánto es el capital que desea poner en riesgo antes de ordenar cualquier transacción.</li>
            <li>Los Mercados Extrabursátiles son considerados mercados de muy alto grado de riesgo, por lo que siempre deberá tomar sus propias decisiones de inversión de conformidad con su propia situación económica, quiere decir, que ninguna transacción puede garantizarle un beneficio o siquiera la evasión de una pérdida, porque todas las operaciones dentro del mercado son operaciones de Riesgo. </li>
            <li>En EL BROKER aconsejamos a todos nuestros clientes siempre poseer suficiente información sobre la transacción en concreto y tomar en consideración los riesgos de la misma antes de decidir dar la orden para una operación, ya que la cuenta que usted ha abierto , es una cuenta con fines especulativos, por lo que el capital que decida usted ingresar al mercado en cada operación es capital 100% en riesgo; por lo anterior, si en algún momento usted no se encuentra seguro de una operación, le pedimos no realizarla. </li>
            <li>El cliente deberá tomar siempre en consideración que cualquier cantidad que éste decida ingresar a cualquier operación, es un capital que puede ser perdido en su totalidad, por lo que el cliente reconoce que en cualquier transacción que éste realice, tiene conciencia de que puede tener una merma considerable del dinero que ingresa como garantía del mismo debido al alto nivel de apalancamiento que éste maneja. Esta pérdida podría darse en cualquier momento, sin importar la duración de la transacción, el activo operado, o las condiciones que se pudieran presentar.</li>
            <li>El cliente acepta y reconoce que asume bajo su propia responsabilidad y riesgo cualquier operación que éste ordene, por lo tanto deslinda de cualquier responsabilidad a EL BROKER por cualquier pérdida que pudiera presentarse en las operaciones que el cliente ejecute.</li>
            <li>El cliente comprende que estas cláusulas de riesgo, enumeran únicamente algunos de los riesgos de operar Contratos por Diferencia, por lo que éste se compromete motu-proprio a obtener más informaciones sobre los riesgos inherentes a este tipo de transacciones.</li>
        </ol>
        <p>Al firmar el presente formato, reconozco haber recibido, leído, entiendo y estar de acuerdo con los términos y condiciones establecidos en el acuerdo con el cliente a través del Contrato de Apertura.</p>
        <h3 class="text-warning">Advertencia de riesgos:</h3>
        <p>Este aviso puede no incluir todos los riesgos asociados con los productos que ponemos a su disposición. Usted no debe invertir ni negociar ningún producto financiero a menos que comprenda su naturaleza y el alcance de su exposición al riesgo. También debe estar seguro de que es adecuado para usted a la luz de sus circunstancias y posición financiera. Los diferentes productos de inversión tienen diferentes niveles de exposición a los riesgos y a diferentes combinaciones de riesgos.</p>
        <p>Todas las inversiones implican un grado de riesgo de algún tipo. Esta sección describe algunos de los riesgos que podrían ser relevantes para los servicios que le brindamos. Podemos proporcionarle más información sobre el riesgo durante el transcurso de nuestros servicios, según corresponda.</p>
        <p>Nuestros servicios se relacionan con ciertas inversiones cuyos precios dependen de las fluctuaciones en los mercados financieros fuera de nuestro control. Las inversiones y los ingresos derivados de ellas pueden bajar o subir y usted puede recuperar menos de lo que invirtió.
            El desempeño pasado no es una guía para el desempeño futuro. El valor de su inversión puede caer y es posible que no recupere la cantidad invertida.</p>
        <p>No debe invertir ni negociar ningún producto financiero a menos que comprenda su naturaleza y el alcance de su exposición y riesgos asociados, y los servicios de inversión discutidos u ofrecidos por nosotros pueden no ser adecuados para todos los inversores. Si tiene alguna duda sobre los méritos o la idoneidad de una inversión, debe buscar el asesoramiento de un asesor financiero independiente.</p>
        <p>La información contenida en nuestros documentos y este sitio web no tiene en cuenta los objetivos de inversión específicos o la situación financiera de ninguna persona. No es una recomendación personal y no debe considerarse como una invitación o invitación a actuar sobre los instrumentos mencionados.</p>
        <p>El rendimiento bruto estimado no es un indicador confiable de los rendimientos futuros. Las inversiones pueden no replicar exactamente la cartera relevante debido a la diferencia en el momento de las inversiones iniciales o la diferencia de reequilibrio resultante de los límites mínimos de tamaño de la transacción.</p>
        <p>EL BROKER se centra principalmente en la provisión de inversiones y servicios que se consideran inversiones de alto riesgo o "especulativas". Las inversiones en pequeñas empresas, productos derivados e inversiones que no son fácilmente realizables se consideran inversiones de alto riesgo y no son adecuadas para todos los inversores. Las inversiones de alto riesgo o especulativas generalmente no son adecuadas para los inversores que buscan preservar el capital o obtener ingresos a través de la inversión. Las inversiones en productos de alto riesgo solo deben considerarse aptas para inversores de alto riesgo o como parte de una cartera de inversiones global equilibrada.</p>
        <p>Este sitio web no tiene en cuenta los objetivos de inversión específicos, la situación financiera o los requisitos específicos de los usuarios individuales. Por lo tanto, debe considerar cuidadosamente su situación financiera y consultar a sus asesores financieros sobre la idoneidad de su situación antes de realizar una inversión o realizar una transacción.</p>
        <p>Tenga en cuenta los siguientes factores de riesgo que, aunque importantes, no se puede usar todos los riesgos asociados con un producto de inversión:</p>
        <h4><b>No todos los productos financieros son adecuados para todos los inversionistas:</b></h4>
        <p>Antes de iniciar cualquier transacción, debe asegurarse de comprender y hacer una evaluación independiente de la idoneidad y adecuación de la transacción en la que ingresa y la naturaleza y el alcance de su exposición al riesgo de pérdida a la luz de sus propios objetivos. recursos financieros y operacionales y otras circunstancias relevantes.</p>
        <p>Todas las inversiones implican un grado de riesgo. El valor de una inversión puede subir o bajar y es posible que no recupere el dinero que invirtió. No debe suponerse que el valor de las inversiones siempre aumenta.</p>
        <p>Debe asegurarse de tener la capacidad financiera para asumir el riesgo y solo invertir una cantidad que esté dispuesto a perder. Los inversores deben construir una cartera diversificada para distribuir el riesgo.</p>
        <p>Las inversiones especulativas o de mayor riesgo tienen mayores márgenes entre los precios y pueden ser difíciles de liquidar a cualquier precio.</p>
        <p>Al comprometer fondos para inversiones de alto riesgo, es posible que no pueda realizar su inversión dentro de su escala de tiempo general, si es que lo hace (es decir, cuánto tiempo le tomará recuperar su dinero).</p>
        <p>Algunas inversiones, como los contratos por diferencias, ETIM, ETF y otros productos, utilizan apalancamiento que puede magnificar las ganancias pero igualmente puede aumentar las pérdidas. Los productos apalancados pueden perder inversores más de lo que inicialmente invirtieron.</p>
        <p>No debe involucrarse en el trading de productos apalancados a menos que comprenda la naturaleza de la transacción que está realizando, el riesgo involucrado y el verdadero alcance de su exposición al riesgo de pérdida.</p>
        <p>Los inversores deben considerar cuidadosamente sus propias circunstancias financieras personales antes de comerciar en los mercados. Si tiene alguna duda sobre la idoneidad de una inversión, debe buscar asesoramiento profesional.</p>
        <p>Los productos de márgenes de negociación, que incluyen apalancamiento como divisas, CFDs y spread-betting en divisas, productos básicos, índices, renta fija y acciones, conllevan un alto nivel de riesgo y pueden no ser adecuados para todos los inversores. El alto nivel de apalancamiento puede funcionar en su contra y en su favor. Considere cuidadosamente sus objetivos de inversión, nivel de experiencia y perfil de riesgo antes de decidir comercializar productos de margen. Debe buscar asesoramiento de un asesor financiero independiente si tiene alguna duda.</p>
        <p>Al realizar operaciones de CFD, ETIM, ETF y Spread-Betting, está sujeto a un nivel de riesgo mayor que los riesgos asociados con las transacciones en acciones tradicionales. Es posible que no recupere el monto inicialmente invertido y que se le solicite realizar pagos adicionales mediante pagos de margen con frecuencia. Los inversores en CFDs, ETIM, ETF pueden estar sujetos a pérdidas ilimitadas.</p>
        <p>No debe negociar en CFDs, ETIM, ETF o Spread Bets a menos que comprenda su naturaleza y el alcance de su exposición al riesgo. También debe estar seguro de que el producto es adecuado para usted a la luz de sus circunstancias y posición financiera. Aunque CFDs ETIM, ETF y Spread Bets pueden utilizarse para la gestión del riesgo de inversión, puede no ser adecuado para algunos inversores. Al decidir si negocia con CFD, ETIM, ETF y Spread Bets, debe tener en cuenta los siguientes puntos:</p>
        <p>Invertir en CFDs ETIM, ETF y Spread Bets conlleva los mismos riesgos que invertir en un futuro, una opción u otro producto derivado. Las transacciones en CFDs ETIM, ETFs y Spread Bets también pueden tener un pasivo contingente y usted debe conocer las implicaciones de esto.
            Los mercados pueden ser volátiles y puede ser difícil o imposible liquidar una posición:</p>
        <p>Bajo ciertas condiciones comerciales, puede ser difícil o imposible liquidar una posición. Esto puede ocurrir, por ejemplo, en momentos de movimientos rápidos de precios si el precio sube o baja en una sesión de negociación o bien puede darse el caso de que no se encuentre una contraparte para liquidar su transacción.</p>
        <h4><b>Las transacciones realizadas con Stop Loss no garantizan que su pérdida se limite a la cantidad prevista:</b></h4>
        <p>La colocación de Stop Order no garantizado no necesariamente limitará sus pérdidas a los montos previstos, porque las condiciones del mercado pueden imposibilitar la ejecución de dicha Orden si el mercado subyacente se mueve directamente a través del precio estipulado.</p>
        <p>Las transacciones en contratos de divisas conllevan un alto grado de riesgo y pueden no ser adecuadas para todos los inversores. El "apalancamiento" que a menudo se puede obtener en el comercio de divisas significa que un movimiento de mercado relativamente pequeño puede conducir a un movimiento proporcionalmente mucho mayor en el valor de su responsabilidad. Antes de decidir operar divisas, debe considerar cuidadosamente sus objetivos de inversión, nivel de experiencia y apetito por el riesgo. Existe la posibilidad de que pueda perder una parte o la totalidad de su inversión inicial y, por lo tanto, no debe invertir dinero que no puede permitirse perder.</p>
        <p>Debe tener en cuenta todos los riesgos asociados con el comercio de divisas y buscar asesoramiento de un asesor financiero independiente si tiene alguna duda.</p>
        <p>Las transacciones de pasivos contingentes, tales como CFDs, ETIM, ETFs y Spread Bets y otros productos financieros negociados con margen, requerirán que realice una serie de pagos contra el precio de compra, en lugar de pagar el precio de compra completo de inmediato.</p>
        <br>
        <p>Si realiza operaciones con CFD, ETIM, ETF y Spread Bets u otros productos negociados con margen, puede sufrir una pérdida total del margen que deposita para establecer o mantener un puesto. Si el mercado se mueve en su contra, es posible que se le pida que pague un monto sustancial de dinero adicional o margen con poca anticipación para mantener el puesto. Si no lo hace dentro del tiempo requerido, su posición puede ser liquidada por una pérdida y usted será responsable por cualquier déficit resultante.</p>
        <p>Incluso si una transacción no está con base marginal, aún puede conllevar la obligación de realizar pagos adicionales en ciertas circunstancias además del monto pagado cuando usted firmó el contrato.</p>
        <p>Las operaciones en CFDs, ETIMs, ETFs y Spread Bets se llevarán a cabo para usted siempre que sea posible en o bajo las reglas de un intercambio de inversión reconocido o designado. Sin embargo, las transacciones de pasivo contingente celebradas por usted que no se negocien en o bajo las reglas de un intercambio de inversión reconocido o designado (como transacciones de divisas) pueden exponerlo a riesgos sustancialmente mayores.</p>
        <p>Antes de comenzar a operar, debe obtener detalles de todas las comisiones y otros cargos por los cuales será responsable. Si los cargos no se expresan en términos de dinero (pero, por ejemplo, como un porcentaje del valor del contrato), debe obtener una explicación clara y por escrito, incluidos ejemplos apropiados, para establecer lo que dichos cargos probablemente signifiquen en términos monetarios específicos. </p>
        <p>Los fondos cotizados en bolsa (ETF) son fondos de inversión, similares a fideicomisos de unidades y OEIC, pero se negocian como acciones. Los ETF siguen de cerca el rendimiento de un índice y, como tal, su valor puede bajar o subir y usted puede recuperar menos de lo que invirtió. Además, el rendimiento pasado no es un indicador confiable del rendimiento futuro.</p>
        <p>El valor de un ETF puede verse afectado por los valores de mercado, las tasas de interés, los tipos de cambio, la volatilidad, los rendimientos de los dividendos y las calificaciones crediticias de los emisores. Estos factores están interrelacionados de maneras complejas, y como resultado, el efecto de cualquier factor puede ser compensado o magnificado por el efecto de otro factor. Debe asegurarse de que el ETF cumpla con sus propios objetivos y circunstancias y considere los posibles riesgos y beneficios de comprar el ETF.</p>
        <p>Le recomendamos fehacientemente que antes de ingresar cualquier operación, no importando la cantidad de veces que usted la haya realizado, se cerciore de conocer los riesgos, movimientos, y mercados implícitos. EL BROKER no asumirá ninguna responsabilidad por transacciones que hayan sido ordenadas por el cliente ni por movimientos adversos a la cuenta del mismo.</p>
        <h1>POLÍTICA DE PRIVACIDAD</h1>
        <h4><b>Aviso de privacidad del cliente</b></h4>
        <p>Proteger su privacidad es importante para EL BROKER y nuestros empleados. Creemos que la confidencialidad y protección de la información del cliente es una de nuestras responsabilidades más fundamentales. Si usted es un cliente existente o está considerando una relación con nosotros, tiene interés en cómo recopilamos, usamos, conservamos y protegemos la información personal no pública. Y si bien la información es fundamental para brindar servicios de calidad, reconocemos que uno de nuestros activos más importantes es la confianza de nuestros clientes.</p>
        <p>Si cambiamos nuestras políticas de privacidad, se publicará de inmediato un aviso de privacidad del cliente en nuestro sitio web. Usted acuerda aceptar la publicación de un aviso revisado de privacidad del cliente electrónicamente en el sitio web como un aviso real para usted. Debe revisar el aviso de privacidad del cliente periódicamente para mantenerse informado de cualquier cambio. Cualquier disputa entre usted y EL BROKER está sujeta a los términos y condiciones de nuestro acuerdo de cliente y nuestras políticas generales, términos y procedimientos que rigen el cliente de EL BROKER y otras cuentas, incluido, cuando corresponda, el arbitraje de disputas y la limitación de daños y perjuicios.
            Si tiene alguna pregunta que este aviso de privacidad del cliente no aborda o si desea analizar las políticas de privacidad de EL BROKER en mayor detalle, comuníquese con nuestro Servicio al Cliente al +852 300 85680 o escríbanos a EL BROKER, Atención: Departamento de Servicio al Cliente, cliente. service@c1broker.com</p>
        <h4><b>La información que recopilamos</b></h4>
        <p>EL BROKER puede recopilar información personal no pública sobre usted de las siguientes fuentes:</p>
        <ol>
            <li>Información que nos proporciona sobre la documentación de apertura de cuenta, aplicaciones, suscripciones u otros formularios;</li>
            <li>Transacciones con nosotros, nuestros afiliados u otros;</li>
            <li>De terceros no afiliados (por ejemplo, agencias de informes de crédito y otros).</li>
        </ol>
        <h4><b>Categorías de información que podemos divulgar</b></h4>
        <p>Podemos divulgar los siguientes tipos de información personal no pública sobre usted:</p>
        <ol>
            <li>Información que recibimos en solicitudes u otros formularios, como nombre, dirección, número de seguro social y dirección de correo electrónico;</li>
            <li>Información sobre sus transacciones con nosotros, nuestros afiliados u otros;</li>
            <li>Información que recibimos de una agencia de informes del consumidor, como la solvencia crediticia y el historial crediticio.</li>
        </ol>
        <h4><b>Partes a las que podemos divulgar información</b></h4>
        <p>No divulgamos información personal no pública a ningún tercero no afiliado, excepto a terceros no afiliados que puedan ayudarnos en el mantenimiento de su cuenta, a instituciones de servicios financieros con quienes tenemos acuerdos de comercialización conjuntos, reguladores a pedido, a otros de conformidad con la citación y de otra manera según lo permita la ley. De vez en cuando, podemos divulgar su información personal no pública a nuestros afiliados, incluidos, entre otros, los corredores-agentes afiliados.
            Si decide cerrar su (s) cuenta (s) o se convierte en un cliente inactivo, continuaremos cumpliendo con la privacidad y las prácticas descritas en este aviso, o avisos subsiguientes, que pueden modificar la política aquí establecida.</p>
        <p>Nada en este aviso de privacidad del cliente tiene la intención de interferir con nuestra capacidad de transferir todo o parte de nuestro negocio y / o activos a un afiliado o tercero no afiliado en cualquier momento, para cualquier propósito, sin ningún tipo de limitación.</p>
        <h4><b>Confidencialidad y procedimientos de seguridad</b></h4>
        <p>EL BROKER toma medidas para salvaguardar la información del cliente y restringir el acceso a su información personal y de cuenta a aquellos empleados que necesitan conocer esa información para que podamos proporcionarle productos o servicios.</p>
        <p>Hacemos hincapié en la importancia de la confidencialidad a través de la capacitación de los empleados, los procedimientos operativos, las políticas escritas y esta política de privacidad. Mantenemos medidas de seguridad físicas, electrónicas y de procedimiento para proteger su información personal no pública.</p>
        <h4><b>Web Sites</b></h4>
        <p>Para proporcionar un mejor servicio y un sitio web más eficaz, utilizamos "Cookies" como parte de nuestra interacción con nuestros clientes que se suscriben al boletín, noticias, informes, estudios y otra información, y podemos utilizar cookies en otros servicios basados en la web que proporcionamos en el futuro. Una "Cookie" es un pequeño archivo de texto que el servidor de nuestra página web coloca en el disco duro del cliente. Las cookies nos ayudan a rastrear los patrones de tráfico para que sepamos qué áreas del sitio web usan nuestros visitantes y para garantizar que solo los miembros u otros usuarios autorizados tengan acceso al sitio del Cliente. Estas galletas no recogen información identificable personalmente.</p>
        <p>Las cookies se usan comúnmente en sitios web y no dañan su sistema. Al configurar sus preferencias u opciones en su navegador, usted determina si se aceptará una Cookie y cómo.</p>
        <h4><b>Términos clave para la privacidad</b></h4>
        <p>"Información personal no pública": información financiera de identificación personal proporcionada por un cliente o cliente potencial a una institución financiera, que resulta de una transacción con el cliente o que la institución financiera obtiene de otra manera en relación con la provisión de un producto o servicio financiero.</p>
        <p>"Afiliado": cualquier entidad que sea parte de la familia de EL BROKER en virtud de la propiedad o control común.</p>
        <p>"Terceros no afiliados": cualquier entidad que no sea parte de la familia de compañías de EL BROKER.</p>
    </div>
</div>